### ISSUE TITLE
showProgressbar settings not working

### ISSUE THREAD

**Issue by davidchriqui** [dennisbaskin/bootstrap-growl-rails#5]
Hi,

Hiding the progress bar from the notification growl doesn't seem to work.

When delay setting is different from 0, whatever the showProgressbar setting is (false or true or not specified), a progress bar is displayed at the bottom of a notification growl.

I'm using Rails 4.2.4.

Thanks for your help.

**Comment by dennisbaskin** [comment]
I would recommend to first verify that you have the setup correct. If so, please verify that this is not just an issue with the JavaScript plugin that this gem uses (http://bootstrap-notify.remabledesigns.com/#growl-documentation). If it is please open a ticket with them. Otherwise, please paste your code, and I can try to help you.

**Comment by rodcrespo** [comment]
@davidchriqui The problem you are having is related to versions. 

The gem is not updated in rubygems.org so the last version it downloads is '3.0.0', instead of 3.1.3 which is the last version of bootstrap-growl-rails.
Until they update the version in rubygems, you can fix the issue adding this to your gemfile:

``` ruby
gem 'bootstrap-growl-rails', git: 'https://github.com/dennisbaskin/bootstrap-growl-rails.git'
```

**Comment by dennisbaskin** [comment]
@davidchriqui @rodcrespo Apparently I have not pushed the latest update to 3.1.3 to RubyGems, but have just done that. You should be able to use it with RubyGems as your source now. I hope 3.1.3 fixes your issue @davidchriqui.
